url: http://writing.drab-makyo.com
name: Writing - Drab Makyo
description: Writing (on various topics) from Madison Scott-Clary


future:      true
markdown:    kramdown
permalink:   pretty
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
